using Cosmogenesis.Generator.Models;
using Cosmogenesis.Generator.Plans;

namespace Cosmogenesis.Generator.Writers.Partition;
static class ReadOrThrowWriter
{
    public static void Write(OutputModel outputModel, DatabasePlan databasePlan, PartitionPlan partitionPlan)
    {
        var s = $@"
namespace {databasePlan.Namespace};

public class {partitionPlan.ReadOrThrowClassName}
{{
    protected virtual {databasePlan.Namespace}.{databasePlan.DbClassName} {databasePlan.DbClassName} {{ get; }} = default!;
    protected virtual Microsoft.Azure.Cosmos.PartitionKey PartitionKey {{ get; }} = default!;

    /// <summary>Mocking constructor</summary>
    protected {partitionPlan.ReadOrThrowClassName}() {{ }}

    internal protected {partitionPlan.ReadOrThrowClassName}(
        {databasePlan.Namespace}.{databasePlan.DbClassName} {databasePlan.DbClassNameArgument},
        Microsoft.Azure.Cosmos.PartitionKey partitionKey)
    {{
        this.{databasePlan.DbClassName} = {databasePlan.DbClassNameArgument} ?? throw new System.ArgumentNullException(nameof({databasePlan.DbClassNameArgument}));
        this.PartitionKey = partitionKey;
    }}

{string.Concat(partitionPlan.Documents.Select(x => ReadOrThrow(databasePlan, x)))}
{Unions(databasePlan, partitionPlan)}
}}
";

        if (partitionPlan.Unions.Count > 0)
        {
            ReadOrThrowUnionsWriter.Write(outputModel, databasePlan, partitionPlan);
        }

        outputModel.Context.AddSource($"partition_{partitionPlan.ReadOrThrowClassName}.cs", s);
    }

    static string Unions(DatabasePlan databasePlan, PartitionPlan partitionPlan) =>
        partitionPlan.Unions.Count == 0 ? "" : $@"
    {databasePlan.Namespace}.{partitionPlan.ReadOrThrowUnionsClassName}? {partitionPlan.ReadOrThrowUnionsClassName.ToArgumentName()};
    public virtual {databasePlan.Namespace}.{partitionPlan.ReadOrThrowUnionsClassName} {partitionPlan.ReadOrThrowUnionsClassName} => {partitionPlan.ReadOrThrowUnionsClassName.ToArgumentName()} ??= new(
        {databasePlan.DbClassNameArgument}: this.{databasePlan.DbClassName},
        partitionKey: this.PartitionKey);
";

    static string ReadOrThrow(DatabasePlan databasePlan, DocumentPlan documentPlan) => $@"
    /// <summary>
    /// Try to load a {documentPlan.ClassName} by id.
    /// id should be transformed using Cosmogenesis.Core.DbDocHelper.GetValidId.
    /// Returns the {documentPlan.ClassName} or throws DbConflictException if not found.
    /// </summary>
    /// <exception cref=""Cosmogenesis.Core.DbOverloadedException"" />
    /// <exception cref=""Cosmogenesis.Core.DbConflictException"" />
    /// <exception cref=""Cosmogenesis.Core.DbUnknownStatusCodeException"" />
    protected virtual async System.Threading.Tasks.Task<{documentPlan.FullTypeName}> {documentPlan.ClassName}ByIdAsync(string id)
    {{
        var result = await this.{databasePlan.DbClassName}.ReadByIdAsync<{documentPlan.FullTypeName}>(
            partitionKey: this.PartitionKey, 
            id: id, 
            type: {documentPlan.ConstDocType}).ConfigureAwait(false);
        if (result is null)
        {{
            throw Cosmogenesis.Core.DbModelFactory.CreateDbConflictException(dbConflictType: Cosmogenesis.Core.DbConflictType.Missing);
        }}
        return result;
    }}

    /// <summary>
    /// Try to load a {documentPlan.ClassName} using an id generated by the parameters.
    /// Returns the {documentPlan.ClassName} or throws DbConflictException if not found.
    /// </summary>
    /// <exception cref=""Cosmogenesis.Core.DbOverloadedException"" />
    /// <exception cref=""Cosmogenesis.Core.DbConflictException"" />
    /// <exception cref=""Cosmogenesis.Core.DbUnknownStatusCodeException"" />
    public virtual async System.Threading.Tasks.Task<{documentPlan.FullTypeName}> {documentPlan.ClassName}Async({documentPlan.GetIdPlan.AsInputParameters()})
    {{
        var result = await this.{databasePlan.DbClassName}.ReadByIdAsync<{documentPlan.FullTypeName}>(
            partitionKey: this.PartitionKey, 
            id: Cosmogenesis.Core.DbDocHelper.GetValidId({documentPlan.GetIdPlan.FullMethodName}({documentPlan.GetIdPlan.AsInputParameterMapping()})), 
            type: {documentPlan.ConstDocType}).ConfigureAwait(false);
        if (result is null)
        {{
            throw Cosmogenesis.Core.DbModelFactory.CreateDbConflictException(dbConflictType: Cosmogenesis.Core.DbConflictType.Missing);
        }}
        return result;
    }}
";
}
